- include: "{{ role_path }}/../common/iptables/iptables-enable-apt.yml"

- name: Install OpenJDK
  apt: package=openjdk-8-jre update_cache=true state=present
  become: true

- name: Check if logstash is installed
  command: dpkg-query -W logstash
  register: logstash_check_deb
  failed_when: logstash_check_deb.rc > 1
  changed_when: logstash_check_deb.rc == 1
  become: true

- name: Download logstash DEB
  get_url: url=https://artifacts.elastic.co/downloads/logstash/logstash-5.1.2.deb dest=/tmp/logstash.deb
  when: logstash_check_deb.rc == 1

- name: Install logstash
  apt: deb=/tmp/logstash.deb
  become: true
  when: logstash_check_deb.rc == 1

- name: Copy over certificates
  copy: src="{{ role_path }}/files/ssl" dest=/etc/logstash/
  become: true

- name: Copy over sub config files
  copy: src="{{ role_path }}/files/conf.d" dest="/etc/logstash/"
  become: true
  notify: Restart Logstash

- name: Copy over Lookups
  copy: src="{{ role_path }}/files/lookups" dest="/etc/logstash/"
  become: true

- name: Add Translate Plugin
  shell: /usr/share/logstash/bin/logstash-plugin install logstash-filter-translate
  become: true
  notify: Restart Logstash

- name: Add Logstash user to ADM group
  user: name=logstash groups=adm append=yes
  become: true

- name: Ensure Service is running
  service: enabled=yes state=started name=logstash
  become: true

#- name: Download GeoIP ASNUm database
#  get_url: url=http://download.maxmind.com/download/geoip/database/asnum/GeoIPASNum.dat.gz dest=/tmp/GeoIPASNum.dat.gz 

#- name: Unzip Geoip
#  shell: gunzip -f /tmp/GeoIPASNum.dat.gz

#- name: Move GeoIP DB
#  shell: mv /tmp/GeoIPASNum.dat /etc/logstash/.
#  become: true

- include: "{{ role_path }}/../common/iptables/iptables-disable-apt.yml"

- name: Create Allow Logstash Chain
  shell: iptables -N LOGSTASH-IN
  become: true
  notify: IPTables Save

- name: Redirect allowed to logstash chain
  iptables: chain=TCP-IN protocol=tcp state=present action=insert ctstate=NEW destination_port=5044 jump=LOGSTASH-IN
  become: true
  notify: IPTables Save

- name: Allow FileBeats Iptables IN
  iptables: chain=LOGSTASH-IN protocol=tcp state=present action=insert ctstate=NEW destination_port=5044 source="{{ hostvars[item]['inventory_hostname'] }}" jump=LOGALLOW
  become: true
  notify: IPTables Save
  with_items: "{{ groups['honeypot'] }}"
