- name: Drop TEMP APT Iptables
  iptables: chain=TCP-OUT protocol=tcp state=absent action=insert ctstate=NEW destination_port=80 jump=LOGALLOW
  become: true

- name: DROP TEMP APT Iptables 443
  iptables: chain=TCP-OUT protocol=tcp state=absent action=insert ctstate=NEW destination_port=443 jump=LOGALLOW
  become: true
